language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - nightly
matrix:
  allow_failures:
    - julia: nightly
cache:
 directories:
   - /home/travis/.julia
addons:
  apt_packages:
    - gfortran


before_install:
- julia -e 'using Pkg; Pkg.update()'


script:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- | 
    if [[ "$TRAVIS_JULIA_VERSION" == "0.6" ]]; then 
      julia -e "Pkg.clone(pwd()); Pkg.test("InfrastructureModels", coverage=true)""
    else
      julia --project --color=yes -e "import Pkg; Pkg.instantiate(); Pkg.build();" #make sure the depedencies are working properly
      julia --check-bounds=yes --depwarn=no --color=yes --project -e "import Pkg; Pkg.test(coverage=true);";  
    fi


after_success:
- |
    if [[ "$TRAVIS_JULIA_VERSION" == "0.6" ]]; then
      julia -e  'using Coverage; cd(Pkg.dir("InfrastructureModels")); LCOV.writefile("lcov.info", process_folder(".")); run(pipeline(`curl -s https://codecov.io/bash`, `bash`))'
      julia -e 'cd(Pkg.dir("InfrastructureModels")); include(joinpath("docs", "make.jl"))'
    else
      julia -e  'using Coverage; import InfrastructureModels; joinpath(dirname(pathof(InfrastructureModels)); LCOV.writefile("lcov.info", process_folder(".")); run(pipeline(`curl -s https://codecov.io/bash`, `bash`))'
      julia -e 'import InfrastructureModels; joinpath(dirname(pathof(InfrastructureModels)); include(joinpath("docs", "make.jl"))'; 
    fi


